// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/yahoo/ads/pb/network/netty/NettyPistachioProtocol.proto

package com.yahoo.ads.pb.network.netty;

public final class NettyPistachioProtocol {
  private NettyPistachioProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    LOOKUP(0, 1),
    STORE(1, 2),
    PROCESS_EVENT(2, 3),
    ;
    
    public static final int LOOKUP_VALUE = 1;
    public static final int STORE_VALUE = 2;
    public static final int PROCESS_EVENT_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static RequestType valueOf(int value) {
      switch (value) {
        case 1: return LOOKUP;
        case 2: return STORE;
        case 3: return PROCESS_EVENT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final RequestType[] VALUES = {
      LOOKUP, STORE, PROCESS_EVENT, 
    };
    
    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private RequestType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:com.yahoo.ads.pb.network.netty.RequestType)
  }
  
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .com.yahoo.ads.pb.network.netty.RequestType type = 1;
    boolean hasType();
    com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType getType();
    
    // optional uint64 id = 2;
    boolean hasId();
    long getId();
    
    // optional uint32 request_id = 3;
    boolean hasRequestId();
    int getRequestId();
    
    // optional uint32 thread_id = 4;
    boolean hasThreadId();
    int getThreadId();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional .com.yahoo.ads.pb.network.netty.RequestType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType getType() {
      return type_;
    }
    
    // optional uint64 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getId() {
      return id_;
    }
    
    // optional uint32 request_id = 3;
    public static final int REQUEST_ID_FIELD_NUMBER = 3;
    private int requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getRequestId() {
      return requestId_;
    }
    
    // optional uint32 thread_id = 4;
    public static final int THREAD_ID_FIELD_NUMBER = 4;
    private int threadId_;
    public boolean hasThreadId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getThreadId() {
      return threadId_;
    }
    
    private void initFields() {
      type_ = com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType.LOOKUP;
      id_ = 0L;
      requestId_ = 0;
      threadId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, requestId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, threadId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, requestId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, threadId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Request_fieldAccessorTable;
      }
      
      // Construct using com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType.LOOKUP;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        threadId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request.getDescriptor();
      }
      
      public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request getDefaultInstanceForType() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request.getDefaultInstance();
      }
      
      public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request build() {
        com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request buildPartial() {
        com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request result = new com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.threadId_ = threadId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request) {
          return mergeFrom((com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request other) {
        if (other == com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasThreadId()) {
          setThreadId(other.getThreadId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType value = com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              requestId_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              threadId_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .com.yahoo.ads.pb.network.netty.RequestType type = 1;
      private com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType type_ = com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType.LOOKUP;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType getType() {
        return type_;
      }
      public Builder setType(com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.RequestType.LOOKUP;
        onChanged();
        return this;
      }
      
      // optional uint64 id = 2;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint32 request_id = 3;
      private int requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(int value) {
        bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 thread_id = 4;
      private int threadId_ ;
      public boolean hasThreadId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getThreadId() {
        return threadId_;
      }
      public Builder setThreadId(int value) {
        bitField0_ |= 0x00000008;
        threadId_ = value;
        onChanged();
        return this;
      }
      public Builder clearThreadId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        threadId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yahoo.ads.pb.network.netty.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yahoo.ads.pb.network.netty.Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint64 id = 1;
    boolean hasId();
    long getId();
    
    // optional bool succeeded = 2;
    boolean hasSucceeded();
    boolean getSucceeded();
    
    // optional string error_message = 3;
    boolean hasErrorMessage();
    String getErrorMessage();
    
    // optional bytes data = 4;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // optional uint32 request_id = 5;
    boolean hasRequestId();
    int getRequestId();
    
    // optional uint32 thread_id = 6;
    boolean hasThreadId();
    int getThreadId();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // optional bool succeeded = 2;
    public static final int SUCCEEDED_FIELD_NUMBER = 2;
    private boolean succeeded_;
    public boolean hasSucceeded() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getSucceeded() {
      return succeeded_;
    }
    
    // optional string error_message = 3;
    public static final int ERROR_MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object errorMessage_;
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes data = 4;
    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // optional uint32 request_id = 5;
    public static final int REQUEST_ID_FIELD_NUMBER = 5;
    private int requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getRequestId() {
      return requestId_;
    }
    
    // optional uint32 thread_id = 6;
    public static final int THREAD_ID_FIELD_NUMBER = 6;
    private int threadId_;
    public boolean hasThreadId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getThreadId() {
      return threadId_;
    }
    
    private void initFields() {
      id_ = 0L;
      succeeded_ = false;
      errorMessage_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
      requestId_ = 0;
      threadId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, succeeded_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, requestId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, threadId_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, succeeded_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getErrorMessageBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, requestId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, threadId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.internal_static_com_yahoo_ads_pb_network_netty_Response_fieldAccessorTable;
      }
      
      // Construct using com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        succeeded_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        requestId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        threadId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response.getDescriptor();
      }
      
      public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response getDefaultInstanceForType() {
        return com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response.getDefaultInstance();
      }
      
      public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response build() {
        com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response buildPartial() {
        com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response result = new com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.succeeded_ = succeeded_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errorMessage_ = errorMessage_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.threadId_ = threadId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response) {
          return mergeFrom((com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response other) {
        if (other == com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSucceeded()) {
          setSucceeded(other.getSucceeded());
        }
        if (other.hasErrorMessage()) {
          setErrorMessage(other.getErrorMessage());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasThreadId()) {
          setThreadId(other.getThreadId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              succeeded_ = input.readBool();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              errorMessage_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              data_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              requestId_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              threadId_ = input.readUInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // optional bool succeeded = 2;
      private boolean succeeded_ ;
      public boolean hasSucceeded() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getSucceeded() {
        return succeeded_;
      }
      public Builder setSucceeded(boolean value) {
        bitField0_ |= 0x00000002;
        succeeded_ = value;
        onChanged();
        return this;
      }
      public Builder clearSucceeded() {
        bitField0_ = (bitField0_ & ~0x00000002);
        succeeded_ = false;
        onChanged();
        return this;
      }
      
      // optional string error_message = 3;
      private java.lang.Object errorMessage_ = "";
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      void setErrorMessage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        errorMessage_ = value;
        onChanged();
      }
      
      // optional bytes data = 4;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // optional uint32 request_id = 5;
      private int requestId_ ;
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getRequestId() {
        return requestId_;
      }
      public Builder setRequestId(int value) {
        bitField0_ |= 0x00000010;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requestId_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 thread_id = 6;
      private int threadId_ ;
      public boolean hasThreadId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getThreadId() {
        return threadId_;
      }
      public Builder setThreadId(int value) {
        bitField0_ |= 0x00000020;
        threadId_ = value;
        onChanged();
        return this;
      }
      public Builder clearThreadId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        threadId_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.yahoo.ads.pb.network.netty.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.yahoo.ads.pb.network.netty.Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yahoo_ads_pb_network_netty_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yahoo_ads_pb_network_netty_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_yahoo_ads_pb_network_netty_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_yahoo_ads_pb_network_netty_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nIsrc/main/java/com/yahoo/ads/pb/network" +
      "/netty/NettyPistachioProtocol.proto\022\036com" +
      ".yahoo.ads.pb.network.netty\"w\n\007Request\0229" +
      "\n\004type\030\001 \001(\0162+.com.yahoo.ads.pb.network." +
      "netty.RequestType\022\n\n\002id\030\002 \001(\004\022\022\n\nrequest" +
      "_id\030\003 \001(\r\022\021\n\tthread_id\030\004 \001(\r\"u\n\010Response" +
      "\022\n\n\002id\030\001 \001(\004\022\021\n\tsucceeded\030\002 \001(\010\022\025\n\rerror" +
      "_message\030\003 \001(\t\022\014\n\004data\030\004 \001(\014\022\022\n\nrequest_" +
      "id\030\005 \001(\r\022\021\n\tthread_id\030\006 \001(\r*7\n\013RequestTy" +
      "pe\022\n\n\006LOOKUP\020\001\022\t\n\005STORE\020\002\022\021\n\rPROCESS_EVE",
      "NT\020\003B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_yahoo_ads_pb_network_netty_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_yahoo_ads_pb_network_netty_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_yahoo_ads_pb_network_netty_Request_descriptor,
              new java.lang.String[] { "Type", "Id", "RequestId", "ThreadId", },
              com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request.class,
              com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Request.Builder.class);
          internal_static_com_yahoo_ads_pb_network_netty_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_yahoo_ads_pb_network_netty_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_yahoo_ads_pb_network_netty_Response_descriptor,
              new java.lang.String[] { "Id", "Succeeded", "ErrorMessage", "Data", "RequestId", "ThreadId", },
              com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response.class,
              com.yahoo.ads.pb.network.netty.NettyPistachioProtocol.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
